apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"    
    istio-injection: disabled          
  name: kserve
---
apiVersion: v1
kind: Service
metadata:
  name: llmisvc-controller-manager-service
  namespace: kserve
  labels:
    app.kubernetes.io/component: controller
    control-plane: llmisvc-controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: llmisvc-controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 8443
    targetPort: metrics
    protocol: TCP
    name: https
