apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llmisvc-serving-cert
  labels:
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
spec:
  commonName: llmisvc-webhook-server-service.kserve.svc
  dnsNames:
  - 'llmisvc-webhook-server-service.{{ .Release.Namespace
    }}.svc'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: llmisvc-webhook-server-cert
