apiVersion: v1
kind: ServiceAccount
metadata:
  name: llmisvc-controller-manager
  labels:
    app.kubernetes.io/component: controller
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.llmisvcControllerManager.serviceAccount.annotations | nindent 4 }}
