apiVersion: v1
kind: Service
metadata:
  name: llmisvc-controller-manager-service
  labels:
    app.kubernetes.io/component: controller
    control-plane: llmisvc-controller-manager
    controller-tools.k8s.io: "1.0"
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmisvcControllerManagerService.type }}
  selector:
    control-plane: llmisvc-controller-manager
    controller-tools.k8s.io: "1.0"
    {{- include "llm-isvc-resources.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.llmisvcControllerManagerService.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: llmisvc-webhook-server-service
  labels:
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmisvcWebhookServerService.type }}
  selector:
    control-plane: llmisvc-controller-manager
    {{- include "llm-isvc-resources.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.llmisvcWebhookServerService.ports | toYaml | nindent 2 }}
