apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: llminferenceservice.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/llmisvc-serving-cert
  labels:
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: llmisvc-webhook-server-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-serving-kserve-io-v1alpha1-llminferenceservice
  failurePolicy: Fail
  name: llminferenceservice.kserve-webhook-server.validator
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llminferenceservices
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: llminferenceserviceconfig.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/llmisvc-serving-cert
  labels:
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: llmisvc-webhook-server-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-serving-kserve-io-v1alpha1-llminferenceserviceconfig
  failurePolicy: Fail
  name: llminferenceserviceconfig.kserve-webhook-server.validator
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - llminferenceserviceconfigs
  sideEffects: None
