name: Kserve localmodel agent Docker Publisher

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: kserve-localmodelnode-agent

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker buildx build . --file localmodel-agent.Dockerfile
          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set registry info based on repo
        run: |
          if [[ "${GITHUB_REPOSITORY}" == "kserve/kserve" ]]; then
            echo "REGISTRY=docker.io" >> $GITHUB_ENV
            echo "IMAGE_ID=kserve/${IMAGE_NAME}" >> $GITHUB_ENV
            echo "REGISTRY_USER=${{ secrets.DOCKER_USER }}" >> $GITHUB_ENV
            echo "REGISTRY_PASS=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          else
            echo "REGISTRY=quay.io" >> $GITHUB_ENV
            echo "IMAGE_ID=quay.io/${{ vars.QUAY_OWNER }}/${IMAGE_NAME}" >> $GITHUB_ENV
            echo "REGISTRY_USER=${{ secrets.QUAY_USER }}" >> $GITHUB_ENV
            echo "REGISTRY_PASS=${{ secrets.QUAY_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: Normalize image name and version
        run: |
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${GITHUB_REF}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          [[ "$VERSION" =~ ^release- ]] && VERSION=$(echo $VERSION | sed 's/^release-//')-latest
          TAGS=$IMAGE_ID:$VERSION
          [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && TAGS=$TAGS,$IMAGE_ID:$(echo $VERSION | sed 's/\(.*\)\.[[:digit:]]\+$/\1/')
          echo CONTAINER_TAGS=$TAGS >> $GITHUB_ENV

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          provenance: false
